title: Coarse Structure/scss
description: >-
  This is going to be a short syllabus I use to quantify my notes at end Coarse
  and engage with the theory in a organized linear fasion.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
